# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19I-r0PILf-wRLD6JSxUeYEZFgpkFaGJL
"""

#Task 1: Calculate Factorial Using a Function:
num = int(input("Enter a number: "))
def factorial(n):
  if n < 2:
    return 1
  else:
    return n * (factorial (n-1))

result = factorial(num)
print(f"Factorial of {num} is: {result}. ")

#Task 1: Calculate Factorial Using a Function:
import math
num = float(input("Enter a number: "))
square_root = math.sqrt(num)
natural_log = math.log(num)
sine_value = math.sin(num)
print(f"Square root: {square_root} ")
print(f"Logarithm: {natural_log}")
print(f"Sine: {sine_value}")